Nex-TON/Nexton_Frontend

src/pages/MyAsset/NFTDetail/NFTDetail.tsx
nft detail page text
lock up period 문구 detail 변경
=> style:nft detail page text change

src/components/common/MainNavigationBar.tsx, src/components/myAsset/Filter/NFTFilter.tsx, src/components/myAsset/NftHeader.tsx, src/components/referral/ReferralPointsExplain.tsx, src/components/stake/Nominator/NominatorItem.tsx, src/pages/Referral/Referral.tsx, src/pages/Stake/NominatorList.tsx
=> feat/renewal in GTM

src/pages/Onboarding/Onboarding.tsx, src/pages/Splash/splash.tsx
onboarding slide 넘어갈 때 이미지 로딩 시간 때문에 싱크가 안맞아서 끊김
image preloading하고 끊기는 느낌 없애기 위해 transition 추가
=> Fix/Onboarding Image, test sync

src/components/main/MainMyAssetInfo.tsx
handleTouchStart 함수 추가해서 swipe 오류 해결
=> Fix:mainmyassetinfo swipe

src/components/loan/History/HistoryListItem.tsx, src/components/loan/Repay/RepayListItem.tsx, src/components/main/ActionCards.tsx, src/components/main/NextonNews.tsx, src/pages/Loan/Loan.tsx, src/pages/MyAsset/NFTDetail/NFTDetail.tsx
=> feat:gtm id 추가

src/context/WalletConnectionProvider.tsx
Fixed tomo wallet disconnection when app closed on telegram mini app environment
=> Tomo persist login

src/components/stake/common/TokensInput.tsx, src/pages/Stake/Amount.tsx
- tomo balance 0일 때 0.00으로 출력
- nxTon 달러로 변환 적용
=> fix:tomo balance 출력 수정

src/hooks/contract/depositTon.js, src/hooks/contract/wrappers/tact_NexTon.ts, src/pages/Stake/NFTPreview.tsx
added bemo staking contract message sending.
=> feat/ strategy staking

src/hooks/contract/depositTon.js
updated mainnet bemo handler address
=> update: mainnet handler address

src/components/main/Menu/AgreementToggle.tsx, src/pages/Main/Main.tsx
main페이지의 이용약관 동의모달 
menu페이지의 privacypolicy, termsofuse둘다 on일경우 뜨지않게 수정
=> agreementModal

src/pages/MyAsset/NFTDetail/NFTDetail.tsx
main페이지의 이용약관 동의모달
menu페이지의 privacypolicy, termsofuse둘다 on일경우 뜨지않게 수정
( wallet disconnet했을시에는 다시뜨는게 맞음 )
=> change agreementModal logic

src/components/stake/Filter/TokenFilterModal.tsx, src/pages/Stake/Amount.tsx
Amount페이지에서 nxTon이 0일때만 changeModal창 뜨게 하기
=> check_nxTon

src/components/exchange/ExchangeConfirmModal.tsx, src/components/stake/common/ExchangePopup.tsx
=> correct word

src/hooks/contract/depositTon.js, src/hooks/contract/useJettonWallet.ts, src/hooks/contract/utils.ts, src/pages/Stake/NFTPreview.tsx
Added: Evaa contract message function.
Update: Moved mapAddress, mapFee functions to util.ts
=> feat/ evaa contract message

src/pages/Stake/NominatorList.tsx
=> hide dedust bot & evaa pool

src/pages/Stake/Amount.tsx
각 balance보여주기 위해 Amount.tsx에서 mapTokenBalance함수 사용
=> fix(Amount): use mapTokenBalance to show balance

src/pages/Stake/NominatorList.tsx
=> remove pool title

src/pages/Stake/NominatorList.tsx
ton&& evaa pool&& 100톤 미만일때 모달창 step1 -> step2로 뜨게 step1 confirmModal창 추가
=> add setp1 modal in evaa pool when staking under 100TON

src/components/main/MainMyAssetInfo.tsx
main, myassetInfo에서 arbitrageBot2,3 정보 막아둠
=> hide arbitrageBot2,3 in MainMyAssetInfo

src/components/dashboard/DashboardTvlTooltip.tsx
=> change_dashboard_toolkit_size

src/components/stake/Nominator/ConfirmNominatorModal.tsx, src/pages/Stake/NominatorList.tsx
usdt일때 evaa pool선택가능 && evaa 제한 2TON미만으로 설정
=> stakinEvaaInUsdt&limitedUnder2Ton

src/components/stake/Filter/TokenFilterModal.tsx
stake/amount 페이지에서 token선택 변경시 amount에 0으로 뜨는 부분 수정
=> fix: change amount 0 to null when select other token in TokenFilterModal

src/components/dashboard/DashboardTvlTooltip.tsx
dashboard/detail toolekit token 이미지 사이즈 조정
=> style: change dashboard/detail toolkit image size

src/components/common/Modal/BasicModal.tsx
add line in blockborrow message
=> style: add line in blockborrow message

src/pages/Unstaking/UnstakingNftDetail.tsx
unstakingNftDetail page의 Rewards 단위 각 토큰 단위로 변경
=> update: change Token Unit in UnstakingNftReward

src/components/main/MainMyAssetInfo.tsx
MainMyAssetInfo Dashboard에서 Bot PNL, Daily PNL, TVL 위치 고정시키기
=> style: fix mainmyassetInfoDashboard InformationTitle position

src/utils/nominator.ts
NFT의 staking info Nominator이름에 각 dedustbot CEX-DEX, DEX-DEX로 나오게 추가
=> update: update NominatorName for dedustBot

src/pages/Stake/NFTPreview.tsx
NFTPreview.tsx에 minting 된 nft 서버 호출에 dedustBot(Arbitrage Bot 2, Arbitrage Bot 3) 추가
=> update: add dedustBot to call nft server

src/pages/Stake/NFTPreview.tsx
NFTPreview.tsx에 USDT tokenSort일때 minting 된 nft 서버 호출에 dedustBot(Arbitrage Bot 2, Arbitrage Bot 3) 추가
=> update: add dedustBot to call nft server when tokenSort is USDT

src/components/dashboard/StrategyRanking.tsx
=> fix: fix dashboard UpcomingBot no.

src/components/stake/Nominator/ConfirmNominatorModal.tsx, src/pages/Stake/NominatorList.tsx
=> update: change limit(2->100) of principal for staking evaa pool

src/pages/Loan/Borrow/BorrowVerify.tsx
changed lend nft receiver according to contract structure change
=> update: lend tx receiver

src/components/myAsset/TotalBalance.tsx, src/pages/Loan/Borrow/BorrowVerify.tsx
changed lend nft receiver according to contract structure change
=> update: lend tx receiver 

src/components/main/Modal/WelcomeModal.tsx
=> fix:alpha version->beta version
